{% set name = "django-braces" %}
{% set version = "1.13.0" %}
{% set sha256 = "ba68e98b817c6f01d71d10849f359979617b3fe4cefb7f289adefddced092ddc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8

about:
  home: https://github.com/brack3t/django-braces
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Reusable, generic mixins for Django '
  description: |
    Mixins for Django's class-based views.
  doc_url: https://django-braces.readthedocs.io/en/latest/
  dev_url: https://github.com/brack3t/django-braces

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
