travis:
  secure:
    BINSTAR_TOKEN: U/BeRpkPd1riB5ieaxmBiYj+9aG7QYAKvWBWcZwquvA2eHU+I2/Qre7xat5diZUjZRaBZ7RpD+/lJ+RdP5PaCAyWHHzaAwVDypJ58WXWFHBS8SlDIeb+/L2969UV1x+T2SdmPPVKURX6mcOrzY62k7OVK1b+7WosL1n0ULWwDHoQl3X6J1D9OiiMVGgtoieOmViyUkob4eV93y92UYsRs+YvppIogQzm19AwUR6bBkOXGxanbxsCVzjaAdPW2x1C312/+2ErDPwaZ1OEHj3QovawD7vQdvrOfH88wGswucq3PomC7lFvuAVbdLZgfNvjwHSW/N5PeLpJuVFcjM1y8fnEL7iSmrE4oooc/ZB9B9q5m976e5Ow5l9l1xV3F6lkEimRZoxarNPwKxk3EVd9X2Nld2OEqFA7JP7jLrsle0/QXeHm2LfgLdlMEFQdttzvftTNz28fnbqtowXinpGzbgq11ZliAM7UXGsKLSBmgGXY/bz0T7PJwnKDwUvj3IrBM7VgnLFxZoXrzya01Qj0uLLHEEYq6KxGMNjir1Lij+YVFVW5Qc+LV5vCglXm6tV8mO+2VMRZnnHXXjf7XTtMxoeFgWo5FrCl0nN05ECPLCqE9YPWr0lJbipnWHioEJUfjudzw49LQCzT0YtaNiLkD+5YKgUgBmHfxshh3GDWvbs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
