travis:
  secure:
    BINSTAR_TOKEN: GUi1jH8Leebk2ELIM0YyPrTzLFhKXEh2H9YAKSIbMnTkqatAdv7VChQynpme5YfTUdaU9SZoTxgBap7wB/8q06yYbihVR9x6fllrIrL75ckNFxzUCvwPkZdRhApJia0EJrRoFLeH2zV7hrD+iYhPgJR1KHfa6NMCpzeP4znaXjrx56gp2+mgPTgEBQe4C42d7dlT4VsSqlzspRm23Tx+elUR7xnAR0SaiD+q2aM9jlZlxurNg/4A2VOl0K7tIJ/DuzrXX5lgvB+fLHwEhSYES8sqtxWNseqUHUE0LGLsrqa8JZ8TuyQyaSThHMSFcUzEWlK6Fw0qMkPE7MYwXtzmFGv72XJmDVv6HKMbPaqPeAkrn/5X7wfV9m600CUIPM36CYD+AnBbSdUw8P/5RhpSOBaf1u1Bzyho8PD3iCxSv4h7MDAONJqgofIuLO/iCtGk6rk+uQtRyBGaiRfsjmIZkS8EjAfNc6uqYCwzqa2j+P5ae0wmiPi8UwdKUWbzZKloxG3LJNTF1wuIGm7DnpUuTslBiWJWO2z6sJCsRN58QiCooIC6gb4Wjb0FA9JqdpFBBFQJaV/vDlRWHRy95yW4Sv1YNM/JXyIF/KXSSDyfRJKTQEn5d2W3MIy57/fnyMfflYQ79R2ZQxPq1X+l/q8ByDwf6uD4HF16M69bgAkdHrA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
